### ISSUE TITLE
Reason for element expressions & directives over properties?

### ISSUE THREAD

**Issue by justinfagnani** [web-padawan/lit-vaadin-helpers#8]
I'm looking at how you're using the new features and seeing what patterns are popping up... I'm wondering why you chose a directive instead of a property, like:

```ts
class DialogDemo extends LitElement {
  render() {
    return html`
      <vaadin-select
        .renderer=${selectRenderer(
          () => html`
            <vaadin-list-box>
              <vaadin-item>Option 1</vaadin-item>
              <vaadin-item>Option 2</vaadin-item>
              <vaadin-item>Option 3</vaadin-item>
            </vaadin-list-box>
          `
        )}
      ></vaadin-select>
    `;
  }
}
```

Do you need the Part object or some other directive capability? Thanks!

**Comment by web-padawan** [comment]
Hi, actually we had a long discussion about the API shape with @Legioth today. This is still not fully decided.

The main benefit of using a property here is better discoverability with `lit-analyzer`. And the original prototype was using this approach.

Then at some point we thought that typing `renderer` twice could be redundant, this was the idea behind choosing element expressions.

**Comment by justinfagnani** [comment]
Ok, good to know! I'm happy to chat about different options if you'd like. I'm curious how these new features evolve into patterns in the community.

**Comment by Legioth** [comment]
Here's some background on the design issues that we're trying to balance between.

In any case, the renderer callback itself always follows this basic format (ignoring optional parameters)
```
(item) => html`Value: ${item.value}`;
```
In the case of renderers that are used for teleporting elements outside the host element's stacking context, the `item` parameter is also omitted.

The two primary syntax options that we're considering are:
* Using a property: `<vaadin-select .renderer=${callback}>`
* Using a directive: `<vaadin-select ${renderer(callback)}>`

There are then also various considerations with naming, but we're trying to focus on the syntax first.

There are also some other variants that could be mentioned even though they are not adding any new aspects to the design space:
* Property with wrapper function: `<vaadin-select .renderer=${wrapperFunction(callback)}>`
* Directive as property value: `<vaadin-select .renderer=${wrapperDirective(callback)}>`
* Directive as element content: `<vaadin-select>${renderer(callback)}`

We have identified three primary aspects to take into account when trying to determine which of those alternatives would be better:
* Discoverability
* Library independence
* Control over re-rendering

### Discoverability
With a property, the IDE can read the TypeScript definitions to offer auto completion for the specific properties that a custom element supports. There is no similar concept for defining that a specific custom element has separate support for a specific directive.

From a semantic point of view, a directive should service the host template rather than serving the component that is defined in that template. That's why we wouldn't even want to suggest improved tooling for connecting a specific directive to a specific component.

### Library independence
We want the Vaadin components to be library agnostic, but at the same time optimized for use with Vaadin's recommended application tech stack that uses `LitElement` for view implementations.

From this perspective, it would be problematic to have a property with a callback that returns `TemplateResult` which is specific to Lit. We are currently in the middle of the messy business of removing Polymer `<template>` support from our components and we would like to avoid doing the same at some point in the future when something even better than Lit comes along.

A directive is a perfect fit here since it's detached from the API of the component itself while still making it possible to provide an opinionated shorthand syntax for the case we want to optimize for.

One considered alternative for using a property would be to also allow returning `null` and in that case the callback would instead have to directly manipulate a DOM element instance that is passed as an additional parameter that can typically be ignored when using Lit. It would thus be possible for someone not using Lit to use a Vaadin component in this way:
```
someVaadinElement.renderer = (item, options) => options.renderRoot.textContent = `Value: ${item.value}`;
```
If go with a directive, then this type of `renderer` property would still exist and the directive would just be a shorthand for assigning its value.

### Control over re-rendering
Inlining an arrow function in the application's `render()` means that the value of a property changes for every render which is typically bad for performance if a new property value causes internals to be refreshed. Assign a reference to a separate function means that the value never changes which is problematic when the render callback isn't a pure function.

The `guard()` directive could be used in either situation, but designing for this approach comes at the expense of developer ergonomics:
* The simplest possible syntax with just an inline arrow function is never the right way
* Refactoring to extract or inline causes changes in behaviour
* There is an additional concept for the developer to master before they can use Vaadin components efficiently

Using a directive makes it possible to make `guard()` functionality a core part of the directive itself. `<vaadin-select ${renderer(callback)}>` would never trigger re-rendering of component internals from `render()`. To explicitly trigger re-rendering for some changed state, the developer would instead type `<vaadin-select ${renderer(callback, [this.stateUsedByCallback])}>`.

Something similar can also be done with a property as long as assigning a new value doesn't trigger internal re-render. We would then instead need a separate way of signalling when re-render is needed. We have so far only identified weird approaches:
* A separate property name that causes re-render for value changes, and requiring the application developer to use `guard()` in this situation: `<vaadin-select .eagerRenderer=${guard([this.stateUsedByCallback], callback)}>`
* A separate property for the dependencies: `<vaadin-select .renderer=${callback} .rendererDependencies=${[this.stateUsedByCallback]}>`
* Wrapping the renderer with something that signals that it's special: `<vaadin-select .renderer=${rendererGuard([this.stateUsedByCallback], callback)}>`. Note that it's not enough to use the regular `guard()` directive since the component itself needs to know whether it's there so that the default can still be to not re-render for new values when using the plain syntax.

This whole line of thought is based on the potentially dangerous assumption that it's a good idea to by default not eagerly re-render. This is maybe not obvious for developers since there wouldn't be anything special like an explicitly declared (potentially empty) `guard()` to show that something special is going on. A developer who observes that their inline arrow function gets invoked repeatedly might have a chance of understanding what goes on, whereas a developer might become terminally stuck in the opposite situation when they would want the renderer to be run again but they cannot figure out how to break out from the guarded default mode.

**Comment by lkraav** [comment]
Nice deep details. 1 month later, is a final decision nearing here?

**Comment by web-padawan** [comment]
Added the above comment to README https://github.com/web-padawan/lit-vaadin-helpers#background
Also note, this isn't part of official Vaadin offering but my personal pet project, at least for the time being. 

We do have issue for moving it to the monorepo in the future https://github.com/vaadin/web-components/issues/266.
And we might consider adding different API (while also keeping the existing directives).

I'm closing this as answered, but feel free to comment if you want to share your opinion 👍
